### PR TITLE
Trial Project Improvement Check

### PR DESCRIPTION
**Pull request by RaoAkif**
I want myself to review my project that was made during our trials at the Microverse. I must give as many review to my project, as much I can. Thanks to my reviewer self.

### CODE REVIEW

**Review by Donard97 — COMMENTED** [review]
## Hi @RaoAkif , 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 

You have submitted a project, without a review. Please review your trial project and submit it for review on the dashboard. You can follow [Github inline comments feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) to guide you on how to review your project. Keep rocking 💪 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by RaoAkif — COMMENTED** [review]
Changes Required !!!

Kindly check my comments and do the required changes.

After making the changes, request for the re-review.

Thanks :)

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## Hi @RaoAkif 👋, 

Good job so far on this special project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [ ]  You did a great job on this special project performing code-review, But there is a little issue with the comments, Please ask the required changes politely to the student, Your comments should look like polite suggestions, not an order. You can use "Please" or "Kindly" to request changes. Apart from this, you did a very great job delivering your first code review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by prolajumokeoni — APPROVED** [review]
Hi @RaoAkif, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._You can also consider:
- You can add emoji's to your comments they make the code review more human-friendly 👽🤖.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
